"use client";

import { useParams, useRouter } from "next/navigation";
import { useEffect, useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { WorkflowLoading } from "@/components/workflow/workflow-loading";
import dynamic from "next/dynamic";

const AILoading = dynamic(() => import("@/components/kokonutui/ai-loading").then(mod => mod.default), {
  ssr: false,
});
import { LOADING_MESSAGES } from "@/lib/loading-messages";

export default function ThesisPage() {
  const params = useParams();
  const router = useRouter();
  const blogPostId = params.blogPostId as string;
  
  const [state, setState] = useState<any>(null);
  const [thesis, setThesis] = useState("");
  const [outline, setOutline] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    loadState();
  }, [blogPostId]);

  const loadState = async () => {
    try {
      const response = await fetch(`/api/workflow/${blogPostId}/state`);
      if (response.ok) {
        const data = await response.json();
        setState(data);
        if (data.thesisOutline?.thesisStatement) {
          setThesis(data.thesisOutline.thesisStatement);
          setOutline(data.thesisOutline.outline || []);
        } else if (!hasAutoGenerated.current) {
          // No thesis exists yet - auto-generate it
          hasAutoGenerated.current = true;
          setLoading(false);
          await handleGenerate();
          return;
        }
      }
    } catch (error) {
      console.error("Error loading state:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);

    try {
      // Get idea from state (which should include the blog post with idea)
      const response = await fetch(`/api/workflow/${blogPostId}/thesis`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          // API will get idea from blog post if not provided
        }),
      });

      if (response.ok) {
        const data = await response.json();
        setThesis(data.thesis);
        setOutline(data.outline || []);
      }
    } catch (error) {
      console.error("Error generating thesis:", error);
      alert("Failed to generate thesis. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = async () => {
    if (!thesis.trim()) return;

    setSubmitting(true);

    try {
      const response = await fetch(`/api/workflow/${blogPostId}/thesis`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          thesis,
          outline,
        }),
      });

      if (response.ok) {
        router.push(`/workflow/${blogPostId}/research`);
      } else {
        const error = await response.json();
        alert(error.error?.message || "Failed to save");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("Failed to save. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <WorkflowLoading
        messages={LOADING_MESSAGES.generic}
        title="Loading Thesis"
      />
    );
  }

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-4xl md:text-5xl font-serif font-bold mb-2 text-foreground">Refine Your Thesis & Outline</h1>
          <p className="text-lg text-muted-foreground">
            {generating 
              ? "Generating your thesis and outline based on your idea..."
              : "Review and edit your thesis statement and outline"}
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Thesis Statement</CardTitle>
            <CardDescription>
              Your main argument or central claim
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {!thesis ? (
              generating ? (
                <div className="flex flex-col items-center py-8">
                  <AILoading
                    loadingStates={LOADING_MESSAGES.thesis.map((text) => ({
                      text,
                      loading: true,
                    }))}
                  />
                </div>
              ) : (
                <Button onClick={handleGenerate} disabled={generating}>
                  Generate Thesis & Outline
                </Button>
              )
            ) : (
              <>
                <Textarea
                  value={thesis}
                  onChange={(e) => setThesis(e.target.value)}
                  className="min-h-[100px]"
                  placeholder="Your thesis statement..."
                />

                <div>
                  <h3 className="font-medium mb-2">Outline</h3>
                  <div className="space-y-3">
                    {outline.map((section: any, index: number) => (
                      <div key={index} className="p-4 border rounded-md bg-gray-50/50">
                        <div className="font-medium text-lg">
                          {section.sectionNumber}. {section.title}
                        </div>
                        <div className="text-sm text-muted-foreground mt-2 space-y-2">
                          <div><strong>Purpose:</strong> {section.purpose}</div>
                          <div className="flex items-center gap-2">
                            <strong>Evidence Type:</strong> 
                            <span className="px-2 py-0.5 bg-secondary/20 rounded text-xs uppercase">{section.evidenceType}</span>
                          </div>
                          {section.evidenceGuidance && (
                            <div className="mt-2 p-3 bg-blue-50 border border-blue-100 rounded-md">
                              <div className="font-medium text-blue-900 text-xs uppercase mb-1">Research Guidance</div>
                              <div className="text-blue-800">{section.evidenceGuidance}</div>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex gap-4 pt-4">
                  <Button
                    variant="outline"
                    onClick={() => router.push(`/workflow/${blogPostId}/voice-tone`)}
                  >
                    Back
                  </Button>
                  <Button
                    variant="outline"
                    onClick={handleGenerate}
                    disabled={generating}
                  >
                    {generating ? "Regenerating..." : "Regenerate"}
                  </Button>
                  <Button
                    onClick={handleSubmit}
                    disabled={!thesis.trim() || submitting}
                    className="flex-1"
                  >
                    {submitting ? "Saving..." : "Continue to Research"}
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

