"use client";

import { useParams, useRouter } from "next/navigation";
import { useEffect, useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { MarkdownViewer } from "@/components/ui/markdown-viewer";
import { Eye, Code } from "lucide-react";
import { WorkflowLoading } from "@/components/workflow/workflow-loading";
import dynamic from "next/dynamic";

const AILoading = dynamic(() => import("@/components/kokonutui/ai-loading").then(mod => mod.default), {
  ssr: false,
});
import { LOADING_MESSAGES } from "@/lib/loading-messages";

export default function DraftPage() {
  const params = useParams();
  const router = useRouter();
  const blogPostId = params.blogPostId as string;
  
  const [draft, setDraft] = useState("");
  const [wordCount, setWordCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [isPreviewFlipped, setIsPreviewFlipped] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    loadState();
  }, [blogPostId]);

  const loadState = async () => {
    try {
      const response = await fetch(`/api/workflow/${blogPostId}/state`);
      if (response.ok) {
        const data = await response.json();
        if (data.draft?.content) {
          setDraft(data.draft.content);
          setWordCount(data.draft.wordCount || 0);
        } else if (!hasAutoGenerated.current) {
          // No draft exists yet, auto-generate it
          hasAutoGenerated.current = true;
          setLoading(false);
          await handleGenerate();
          return;
        }
      }
    } catch (error) {
      console.error("Error loading state:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);

    try {
      const response = await fetch(`/api/workflow/${blogPostId}/draft`, {
        method: "POST",
      });

      if (response.ok) {
        const data = await response.json();
        setDraft(data.content);
        setWordCount(data.wordCount);
      } else {
        const error = await response.json();
        alert(error.error?.message || "Failed to generate draft");
      }
    } catch (error) {
      console.error("Error generating draft:", error);
      alert("Failed to generate draft. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = async (approved: boolean) => {
    setSubmitting(true);

    try {
      const response = await fetch(`/api/workflow/${blogPostId}/draft`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          approved,
          goBackToStep: approved ? undefined : "draft",
        }),
      });

      if (response.ok) {
        if (approved) {
          // Start generating the final post optimistically before navigating
          // This is a fire-and-forget request - the final page will poll for status
          fetch(`/api/workflow/${blogPostId}/editorial`, {
            method: "POST",
          }).catch(console.error);
          
          // Navigate immediately - the final page will show the generation status
          router.push(`/workflow/${blogPostId}/final?generating=true`);
        } else {
          // Regenerate - this will create a new draft version
          setDraft(""); // Clear current draft to show generating state
          await handleGenerate();
        }
      } else {
        const error = await response.json();
        alert(error.error?.message || "Failed to save");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("Failed to save. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <WorkflowLoading
        messages={LOADING_MESSAGES.generic}
        title="Loading Draft"
      />
    );
  }

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-4xl md:text-5xl font-serif font-bold mb-2 text-foreground">Review Your Draft</h1>
          <p className="text-lg text-muted-foreground">
            Review the generated blog post draft
          </p>
        </div>

        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Blog Post Draft</CardTitle>
                <CardDescription>
                  Word Count: {wordCount} words
                </CardDescription>
              </div>
              {draft && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => setIsPreviewFlipped(!isPreviewFlipped)}
                  aria-label={isPreviewFlipped ? "View markdown" : "View preview"}
                >
                  {isPreviewFlipped ? (
                    <>
                      <Code className="mr-2 h-4 w-4" />
                      View/Edit Markdown
                    </>
                  ) : (
                    <>
                      <Eye className="mr-2 h-4 w-4" />
                      View Preview
                    </>
                  )}
                </Button>
              )}
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {!draft ? (
              generating ? (
                <div className="flex flex-col items-center py-8">
                  <AILoading
                    loadingStates={LOADING_MESSAGES.draft.map((text) => ({
                      text,
                      loading: true,
                    }))}
                  />
                </div>
              ) : (
                <Button onClick={handleGenerate} disabled={generating}>
                  Generate Draft
                </Button>
              )
            ) : (
              <>
                <MarkdownViewer 
                  content={draft} 
                  maxHeight="600px" 
                  isFlipped={isPreviewFlipped}
                  onFlipChange={setIsPreviewFlipped}
                />

                <div className="flex gap-4 pt-4">
                  <Button
                    variant="outline"
                    onClick={() => router.push(`/workflow/${blogPostId}/research`)}
                  >
                    Back
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => handleSubmit(false)}
                    disabled={submitting}
                  >
                    Request Changes
                  </Button>
                  <Button
                    onClick={() => handleSubmit(true)}
                    disabled={submitting}
                    className="flex-1"
                  >
                    {submitting ? "Saving..." : "Approve & Continue"}
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

